name: Release

on:
  pull_request:
    types: [closed]
    branches: [master]

jobs:
  release:
    if: github.head_ref == 'release' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Knope
        uses: knope-dev/action@v2.1.2
        with:
          version: 0.22.3
      - run: knope release --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      - uses: actions/setup-node@v4
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun run build:bundle
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
